# Generated by Django 3.0.5 on 2021-10-15 09:47

from django.db import migrations, models
import django.db.models.deletion
import kairos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(default='', max_length=50)),
                ('min', models.CharField(default='', max_length=50)),
                ('max', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCate', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=50)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('adresse', models.CharField(default='', max_length=50)),
                ('tel', models.CharField(default='', max_length=50)),
                ('point', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default='', max_length=50)),
                ('nom', models.CharField(default='', max_length=50)),
                ('categorie', models.CharField(default='', max_length=50)),
                ('prix', models.CharField(default='', max_length=50)),
                ('quantite', models.IntegerField(default=1)),
                ('net', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('facture', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='', max_length=50)),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('nomPro', models.CharField(default='', max_length=50)),
                ('categorie', models.CharField(default='', max_length=50)),
                ('prix', models.CharField(default='', max_length=50)),
                ('quantite', models.CharField(default='', max_length=50)),
                ('net', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('prix', models.FloatField(default=0)),
                ('quantite', models.FloatField(default=0)),
                ('unite', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heureFatcure', models.CharField(default='', max_length=50)),
                ('dateFacture', models.CharField(default='', max_length=50)),
                ('total', models.CharField(default='', max_length=50)),
                ('billet', models.CharField(default='', max_length=50)),
                ('rendu', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ingredient', models.CharField(max_length=50)),
                ('quantite_stock', models.FloatField(blank=True, default='0', null=True)),
                ('achat_montant', models.FloatField(blank=True, default='0', null=True)),
                ('achat_prix_unitaire', models.FloatField(blank=True, default='0', null=True)),
                ('achat_quantite', models.FloatField(blank=True, default='0', null=True)),
                ('achat_date', models.DateTimeField(auto_now=True)),
                ('don_quantite', models.FloatField(blank=True, default='0', null=True)),
                ('alerte_quantite', models.FloatField(blank=True, default='0', null=True)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=kairos.models.nameFile)),
                ('qte_sortie', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kairos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vola_kairos', models.FloatField(default=0)),
                ('recette', models.FloatField(default=0)),
                ('depense', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=50)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.FloatField(max_length=8)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prix', models.CharField(default='', max_length=50)),
                ('cover', models.FileField(blank=True, default='', upload_to=kairos.models.upload_path)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unite', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ingredient', models.FloatField(blank=True, default='1', null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Ingredient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Unite')),
            ],
        ),
        migrations.CreateModel(
            name='Marcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajoute', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_marchers', to='kairos.Ingredient')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Lieu')),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Prix')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='achat_lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Lieu'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_related', to='kairos.CategorieIngredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Unite'),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=50)),
                ('quantite_stock', models.FloatField(blank=True, default='0', null=True)),
                ('achat_lieu', models.CharField(max_length=50)),
                ('achat_montant', models.FloatField(blank=True, default='0', null=True)),
                ('achat_prix_unitaire', models.FloatField(blank=True, default='0', null=True)),
                ('achat_quantite', models.FloatField(blank=True, default='0', null=True)),
                ('sortie_quantite', models.FloatField(blank=True, default='0', null=True)),
                ('don_quantite', models.FloatField(blank=True, default='0', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kairos.Ingredient')),
            ],
        ),
    ]
