# Generated by Django 3.0.5 on 2021-10-11 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilisateur.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=13)),
                ('image', models.FileField(blank=True, default='', upload_to=utilisateur.models.upload_path)),
                ('accounts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
